### PR TITLE
Home recycler fix

### LINKED ISSUE #110: Feed recycler view flickers on item change
`package np.com.naxa.factsnepal.feed.list`
Method used to update the list
```
    public void updateList(List<Fact> newList) {
        ArrayList<Fact> oldList = this.facts;
        this.facts = (ArrayList<Fact>) newList;

        DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(new FactsDiffCallback(oldList, newList));
        diffResult.dispatchUpdatesTo(this);
    }
```

### PR DESCRIPTION
**Pull request by hereyubaraj**
fixes #110

### CODE REVIEW

File: app/src/main/java/np/com/naxa/factsnepal/feed/FactsLocalSource.java [hunk 1]
```diff
@@ -75,8 +79,17 @@ public void save(List<Fact> items) {
...
+
     public LiveData<List<Fact>> getAll() {
-        return factsDAO.getAll();
+        SharedPreferenceUtils utils = SharedPreferenceUtils.getInstance(FactsNepal.getInstance());
+        Set<String> selectedCategories = utils.getSetValue(Constant.SharedPrefKey.SELECTED_CATEGORIES);
+        if (selectedCategories != null && selectedCategories.size() > 0) {
+            Log.d("LocalSource", " category by id called ");
+            return getByIds(selectedCategories);
+        } else {
+            Log.d("LocalSource", " all facts called");
```
Comment (konishon) [inline app/src/main/java/np/com/naxa/factsnepal/feed/FactsLocalSource.java]: Let's remove these debug logs :D

File: app/src/main/java/np/com/naxa/factsnepal/feed/list/resource/FactsRepo.java [hunk 2]
```diff
@@ -63,12 +65,13 @@ private void showMessage(String message) {
...
 
     public Single<List<Fact>> getFactsCategories(boolean refreshCache) {
+        Log.d("FactsRepo", "categories by id called");
         if (refreshCache && NetworkUtils.isConnected()) {
             FactsRemoteSource.getINSTANCE().getCategories()
                     .subscribe(new DisposableObserver<List<Category>>() {
                         @Override
                         public void onNext(List<Category> categories) {
-
+                            Log.d("FactsRepo", "data recieved by categories");
```
Comment (konishon) [inline app/src/main/java/np/com/naxa/factsnepal/feed/list/resource/FactsRepo.java:74]: please remove logs
